[package]
name = "rustystream-ffi"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustystream = { path = "../rustystream" }
futures = "^0.3"
allo-isolate = "^0.1"
async-std = "^1.6"
serde_json = "^1"